import { useEffect, useMemo, useRef, useState } from 'react';
import { useVirtualizer } from '@tanstack/react-virtual';
import { ArrowLeft, CalendarDays, FileJson, Image as ImageIcon, LoaderCircle, Users } from 'lucide-react';
import { Link, useParams, useSearchParams } from 'react-router-dom';
import { database } from '../database/client';
import type { Message, Media } from '../archive/schemas/models';
import type { ConversationPreview, Page } from '../database/types';
import { MediaRenderer } from '../components/MediaRenderer';
import { MediaViewer } from '../components/MediaViewer';
const PAGE_SIZE = 40;
const date = (value?: string) => value ? new Date(value).toLocaleString() : 'Date unavailable';
const day = (value?: string) => value ? new Date(value).toLocaleDateString() : 'Date unavailable';
export function ConversationPage() {
  const { conversationId: routeId } = useParams(), conversationId = decodeURIComponent(routeId ?? ''), [searchParams] = useSearchParams(), highlight = searchParams.get('q') ?? '';
  const [page, setPage] = useState<Page<Message>>({ items: [], hasMore: false }), [conversation, setConversation] = useState<ConversationPreview>(), [loading, setLoading] = useState(true), [loadingMore, setLoadingMore] = useState(false), [error, setError] = useState(''), [viewerIndex, setViewerIndex] = useState<number>();
  const scrollRef = useRef<HTMLDivElement>(null);
  useEffect(() => { let active = true; setLoading(true); setError(''); Promise.all([database.messages(conversationId, { limit: PAGE_SIZE }), database.conversations({ limit: 100 })]).then(([messages, conversations]) => { if (!active) return; setPage(messages); setConversation(conversations.items.find(item => item.id === conversationId)); }).catch(caught => active && setError(caught instanceof Error ? caught.message : String(caught))).finally(() => active && setLoading(false)); return () => { active = false; }; }, [conversationId]);
  const loadOlder = () => { if (!page.nextCursor || loadingMore) return; const before = scrollRef.current?.scrollHeight ?? 0; setLoadingMore(true); database.messages(conversationId, { limit: PAGE_SIZE, cursor: page.nextCursor }).then(next => { setPage(current => ({ ...next, items: [...current.items, ...next.items] })); requestAnimationFrame(() => { if (scrollRef.current) scrollRef.current.scrollTop += (scrollRef.current.scrollHeight - before); }); }).catch(caught => setError(caught instanceof Error ? caught.message : String(caught))).finally(() => setLoadingMore(false)); };
  const visible = useMemo(() => [...page.items].reverse(), [page.items]);
  const mediaItems = useMemo(() => visible.flatMap(message => message.media ?? []), [visible]);
  const virtualized = visible.length > 100;
  const rowVirtualizer = useVirtualizer({ count: virtualized ? visible.length : 0, getScrollElement: () => scrollRef.current, estimateSize: () => 120, overscan: 8 });
  const renderMessage = (message: Message, index: number) => <div key={message.id}>{(index === 0 || day(visible[index - 1]?.sentAt) !== day(message.sentAt)) && <div className="date-separator"><CalendarDays/> {day(message.sentAt)}</div>}<article className={highlight && message.text?.toLocaleLowerCase().includes(highlight.toLocaleLowerCase()) ? 'message-match' : ''}><header><b>{message.senderName || 'Unknown sender'}</b>{message.sentAt && <time>{date(message.sentAt)}</time>}</header>{message.text && <p>{message.text}</p>}{message.media?.length ? <div className="attachment-row">{message.media.map(media => <MediaRenderer key={media.id} media={media} onOpen={() => setViewerIndex(mediaItems.findIndex(item => item.id === media.id))} compact/>)}</div> : null}{message.mediaCount ? <span className="message-media"><ImageIcon/> {message.mediaCount} media reference{message.mediaCount === 1 ? '' : 's'}</span> : null}<small title={message.source.path}><FileJson/> {message.source.path.split('/').pop()}</small></article></div>;
  return <div className="page"><Link className="back" to="/messages"><ArrowLeft/> Conversations</Link><div className="conversation-header"><div><p className="eyebrow">Messenger archive</p><h1 className="section-title">{conversation?.title || 'Conversation'}</h1>{conversation?.participantNames.length ? <p><Users/> {conversation.participantNames.join(', ')}</p> : null}</div>{highlight && <p className="search-context">Showing messages for “{highlight}”.</p>}</div>{loading ? <p className="empty"><LoaderCircle className="spin"/> Loading messages…</p> : error ? <p className="error">{error}</p> : !page.items.length ? <p className="empty">No supported messages were imported.</p> : <><div ref={scrollRef} className="message-list-scroll">{virtualized ? <div style={{ height: rowVirtualizer.getTotalSize(), position: 'relative' }}>{rowVirtualizer.getVirtualItems().map(item => <div key={item.key} ref={rowVirtualizer.measureElement} data-index={item.index} className="virtual-row" style={{ transform: `translateY(${item.start}px)` }}>{renderMessage(visible[item.index], item.index)}</div>)}</div> : <div className="message-list">{visible.map(renderMessage)}</div>}</div>{page.hasMore && <button className="load-more" onClick={loadOlder} disabled={loadingMore}>{loadingMore ? <><LoaderCircle className="spin"/> Loading older messages…</> : 'Load older messages'}</button>}</>}{viewerIndex !== undefined && <MediaViewer items={mediaItems} index={viewerIndex} onClose={() => setViewerIndex(undefined)} onChange={setViewerIndex}/>}</div>;
}
