import { useEffect, useMemo, useRef, useState } from 'react';
import { useVirtualizer } from '@tanstack/react-virtual';
import { ChevronDown, Clock3, FileJson, Image as ImageIcon, LoaderCircle, SlidersHorizontal } from 'lucide-react';
import { database } from '../database/client';
import type { Page } from '../database/types';
import type { Media, Post } from '../archive/schemas/models';
import { useDatabaseQuery } from './useDatabaseQuery';
import { MediaRenderer } from '../components/MediaRenderer';
import { MediaViewer } from '../components/MediaViewer';
import { Link } from 'react-router-dom';
import { PersonDisplay } from '../components/PersonDisplay';
const PAGE_SIZE = 20;
const shownDate = (value?: string) => value ? new Date(value).toLocaleString() : 'Date unavailable in archive';
export function PostsPage() {
  const [sort, setSort] = useState<'newest' | 'oldest'>('newest'), [year, setYear] = useState<number>(), [page, setPage] = useState<Page<Post>>({ items: [], hasMore: false }), [loading, setLoading] = useState(true), [loadingMore, setLoadingMore] = useState(false), [error, setError] = useState(''), [viewerIndex, setViewerIndex] = useState<number>();
  const scrollRef = useRef<HTMLDivElement>(null);
  const { data: stats } = useDatabaseQuery(() => database.stats());
  useEffect(() => { let active = true; setLoading(true); setError(''); database.posts({ limit: PAGE_SIZE, sort, year }).then(next => active && setPage(next)).catch(caught => active && setError(caught instanceof Error ? caught.message : String(caught))).finally(() => active && setLoading(false)); return () => { active = false; }; }, [sort, year]);
  const loadMore = () => { if (!page.nextCursor || loadingMore) return; setLoadingMore(true); database.posts({ limit: PAGE_SIZE, sort, year, cursor: page.nextCursor }).then(next => setPage(current => ({ ...next, items: [...current.items, ...next.items] }))).catch(caught => setError(caught instanceof Error ? caught.message : String(caught))).finally(() => setLoadingMore(false)); };
  const mediaItems = useMemo(() => page.items.flatMap(post => post.media ?? []), [page.items]);
  const virtualized = page.items.length > 60;
  const rowVirtualizer = useVirtualizer({ count: virtualized ? page.items.length : 0, getScrollElement: () => scrollRef.current, estimateSize: () => 210, overscan: 6 });
  const renderPost = (post: Post) => <article key={post.id}><div className="post-author-row"><PersonDisplay compact person={{ id: post.authorId, displayName: post.authorName || (post.authorId === 'owner' ? 'Archive owner' : 'Unknown author'), photoPath: post.authorPhotoPath, archivePartId: post.source.archivePartId }} context={shownDate(post.createdAt)}/><Link className="post-open-link" to={`/posts/${encodeURIComponent(post.id)}`}>Open post</Link></div>{post.title && <h2><Link className="post-title-link" to={`/posts/${encodeURIComponent(post.id)}`}>{post.title}</Link></h2>}<p>{post.text || 'This post has no text content.'}</p>{post.media?.length ? <div className="attachment-row">{post.media.map(media => <MediaRenderer key={media.id} media={media} onOpen={() => setViewerIndex(mediaItems.findIndex(item => item.id === media.id))} compact/>)}</div> : null}{(post.commentCount || post.reactionCount) ? <div className="social-summary"><span>{post.commentCount ?? post.comments?.length ?? 0} comments</span><span>{post.reactionCount ?? post.reactions?.length ?? 0} reactions</span>{post.reactions?.slice(0, 4).map(reaction => <span key={reaction.id} className="reaction-chip">{reaction.personId ? <Link to={`/people/${encodeURIComponent(reaction.personId)}`}>{reaction.kind}{reaction.personName ? ` · ${reaction.personName}` : ''}</Link> : `${reaction.kind}${reaction.personName ? ` · ${reaction.personName}` : ''}`}</span>)}</div> : null}{post.comments?.length ? <div className="comment-list">{post.comments.slice(0, 8).map(comment => <div key={comment.id}><b>{comment.authorId ? <Link to={`/people/${encodeURIComponent(comment.authorId)}`}>{comment.authorName ?? 'Unknown person'}</Link> : comment.authorName ?? 'Unknown person'}</b><span>{comment.text}</span></div>)}{post.comments.length > 8 && <small>Showing 8 of {post.comments.length} comments.</small>}</div> : null}<footer><span><Clock3/> {shownDate(post.createdAt)}</span>{post.mediaCount ? <span><ImageIcon/> {post.mediaCount} media reference{post.mediaCount === 1 ? '' : 's'}</span> : null}<span title={post.source.path}><FileJson/> {post.source.path.split('/').pop()}</span></footer></article>;
  return <div className="page home-page"><div className="page-heading-row"><div><p className="eyebrow">Your archive home</p><h1 className="section-title">Home</h1><p className="section-lead">A chronological stream reconstructed from the records in this archive.</p></div><div className="filter-row"><label><SlidersHorizontal/> Order<select value={sort} onChange={event => setSort(event.target.value as 'newest' | 'oldest')}><option value="newest">Newest first</option><option value="oldest">Oldest first</option></select><ChevronDown/></label><label>Year<select aria-label="Filter by year" value={year ?? ''} onChange={event => setYear(event.target.value ? Number(event.target.value) : undefined)}><option value="">All years</option>{stats?.years.map(value => <option key={value} value={value}>{value}</option>)}</select><ChevronDown/></label></div></div>{loading ? <p className="empty"><LoaderCircle className="spin"/> Loading posts from SQLite…</p> : error ? <p className="error">{error}</p> : !page.items.length ? <p className="empty">No supported text posts match this filter.</p> : <>{virtualized ? <div ref={scrollRef} className="virtual-list"><div style={{ height: rowVirtualizer.getTotalSize(), position: 'relative' }}>{rowVirtualizer.getVirtualItems().map(item => <div key={item.key} ref={rowVirtualizer.measureElement} data-index={item.index} className="virtual-row" style={{ transform: `translateY(${item.start}px)` }}>{renderPost(page.items[item.index])}</div>)}</div></div> : <div className="post-list">{page.items.map(renderPost)}</div>}{page.hasMore && <button className="load-more" onClick={loadMore} disabled={loadingMore}>{loadingMore ? <><LoaderCircle className="spin"/> Loading more…</> : 'Load older posts'}</button>}</>}<HomeContext stats={stats}/>{viewerIndex !== undefined && <MediaViewer items={mediaItems} index={viewerIndex} onClose={() => setViewerIndex(undefined)} onChange={setViewerIndex}/>}</div>;
}
function HomeContext({ stats }: { stats?: { earliest?: string; latest?: string; media: number; people: number } }) {
  const [memories, setMemories] = useState<{ yearsAgo: number; summary: string }[]>([]);
  useEffect(() => { const today = new Date(); database.memories(today.getUTCMonth() + 1, today.getUTCDate(), { limit: 3 }).then(items => setMemories(items.map(item => ({ yearsAgo: item.yearsAgo, summary: item.summary })))).catch(() => undefined); }, []);
  return <aside className="home-context"><section className="panel"><h2>Archive context</h2><p>{stats?.people ?? 0} people · {stats?.media ?? 0} media references</p>{stats?.earliest && stats.latest && <p>Archive span<br/><b>{new Date(stats.earliest).getUTCFullYear()}–{new Date(stats.latest).getUTCFullYear()}</b></p>}</section><section className="panel"><h2>Memories</h2>{memories.length ? memories.map(item => <p key={`${item.yearsAgo}:${item.summary}`}><b>{item.yearsAgo ? `${item.yearsAgo} year${item.yearsAgo === 1 ? '' : 's'} ago` : 'This year'}</b><br/>{item.summary}</p>) : <p>No memories found for today.</p>}<Link className="text-link" to="/memories">Open Memories →</Link></section><section className="panel"><h2>Read-only archive</h2><p>Historical records only. Nothing here changes Facebook data.</p><Link className="text-link" to="/activity">View Activity →</Link></section></aside>;
}
