import { useEffect, useState } from 'react';
import { Clock3, FileJson, LoaderCircle, MessageCircle, MessagesSquare, Search as SearchIcon, UserRound, Users, Image, Heart, MessageSquare } from 'lucide-react';
import { Link } from 'react-router-dom';
import { database } from '../database/client';
import type { SearchResponse, SearchResult } from '../database/types';
const labels: Record<string, string> = { post: 'Posts', message: 'Messages', conversation: 'Conversations', person: 'People', comment: 'Comments', reaction: 'Reactions', connection: 'Connections', album: 'Albums', 'profile-fact': 'About' };
const icons: Record<string, typeof FileJson> = { post: FileJson, message: MessageCircle, conversation: MessagesSquare, person: UserRound, comment: MessageSquare, reaction: Heart, connection: Users, album: Image, 'profile-fact': UserRound };
const date = (value?: string) => value ? new Date(value).toLocaleString() : '';
const blank: SearchResponse = { items: [], counts: {}, hasMore: false, backend: 'fts5' };
function Snippet({ result }: { result: SearchResult }) {
  const value = result.snippet || result.body || result.context || 'No text preview';
  const parts = value.split(/(\[\[H\]][\s\S]*?\[\[\/H\]\])/g);
  return <strong>{parts.map((part, index) => part.startsWith('[[H]]') ? <mark key={index}>{part.slice(5, -6)}</mark> : <span key={index}>{part}</span>)}</strong>;
}
export function SearchPage() {
  const [query, setQuery] = useState(''), [applied, setApplied] = useState(''), [filter, setFilter] = useState('all'), [year, setYear] = useState(''), [from, setFrom] = useState(''), [to, setTo] = useState(''), [result, setResult] = useState<SearchResponse>(blank), [loading, setLoading] = useState(false), [loadingMore, setLoadingMore] = useState(false), [error, setError] = useState('');
  useEffect(() => { const timer = window.setTimeout(() => setApplied(query.trim()), 300); return () => window.clearTimeout(timer); }, [query]);
  const entityType = filter === 'all' ? undefined : filter;
  const searchOptions = { entityType, year: year ? Number(year) : undefined, from: from || undefined, to: to || undefined };
  useEffect(() => { let active = true; if (!applied) { setResult(blank); setLoading(false); return; } setLoading(true); setError(''); database.search(applied, { ...searchOptions, limit: 30 }).then(next => active && setResult(next)).catch(caught => active && setError(caught instanceof Error ? caught.message : String(caught))).finally(() => active && setLoading(false)); return () => { active = false; }; }, [applied, entityType, year, from, to]);
  const loadMore = () => { if (!result.nextCursor || loadingMore) return; setLoadingMore(true); database.search(applied, { ...searchOptions, limit: 30, cursor: result.nextCursor }).then(next => setResult(current => ({ ...next, items: [...current.items, ...next.items], counts: Object.entries({ ...current.counts, ...next.counts }).reduce<Record<string, number>>((counts, [type]) => { counts[type] = (current.counts[type] ?? 0) + (next.counts[type] ?? 0); return counts; }, {}) }))).catch(caught => setError(caught instanceof Error ? caught.message : String(caught))).finally(() => setLoadingMore(false)); };
  const groups = Object.keys(labels).map(type => ({ type, items: result.items.filter(item => item.entityType === type) })).filter(group => group.items.length);
  const destination = (item: SearchResult) => item.entityType === 'post' ? `/posts/${encodeURIComponent(item.entityId)}` : item.entityType === 'comment' ? (item.context ? `/posts/${encodeURIComponent(item.context)}` : '/activity') : item.entityType === 'message' && item.conversationId ? `/messages/${encodeURIComponent(item.conversationId)}?q=${encodeURIComponent(applied)}` : item.entityType === 'conversation' ? `/messages/${encodeURIComponent(item.entityId)}` : item.entityType === 'connection' ? '/friends' : item.entityType === 'album' ? `/albums/${encodeURIComponent(item.entityId)}` : item.entityType === 'profile-fact' ? '/profile' : `/people/${encodeURIComponent(item.entityId)}`;
  return <div className="page"><p className="eyebrow">Local archive index</p><h1 className="section-title">Search</h1><p className="section-lead">Search runs inside SQLite FTS5 when available; ranking and pagination are computed locally.</p><label className="global-search"><SearchIcon/><input autoFocus value={query} onChange={event => setQuery(event.target.value)} placeholder="Search posts, messages, people…" aria-label="Search archive"/></label><div className="search-filter-row"><label className="search-filter"><span>Search in</span><select aria-label="Search type" value={filter} onChange={event => setFilter(event.target.value)}><option value="all">All records</option><option value="post">Posts</option><option value="message">Messages</option><option value="person">People</option><option value="conversation">Conversations</option><option value="comment">Comments</option><option value="reaction">Reactions</option><option value="media">Media metadata</option></select></label><label className="search-filter"><span>Year</span><input aria-label="Search year" inputMode="numeric" pattern="[0-9]*" value={year} onChange={event => setYear(event.target.value.replace(/[^0-9]/g, '').slice(0, 4))} placeholder="Any"/></label><label className="search-filter"><span>From</span><input aria-label="Search from date" type="date" value={from} onChange={event => setFrom(event.target.value)}/></label><label className="search-filter"><span>To</span><input aria-label="Search to date" type="date" value={to} onChange={event => setTo(event.target.value)}/></label></div>{loading ? <p className="empty"><LoaderCircle className="spin"/> Searching locally…</p> : error ? <p className="error">{error}</p> : !applied ? <p className="empty search-hint">Type a word or phrase to search your imported archive.</p> : !groups.length ? <p className="empty">No results for “{applied}”.</p> : <><div className="search-results">{groups.map(group => { const GroupIcon = icons[group.type] ?? FileJson; return <section className="search-group" key={group.type}><div className="group-heading"><h2>{labels[group.type] ?? group.type}</h2><span>{result.counts[group.type] ?? group.items.length}</span></div>{group.items.map(item => <Link className="search-result" key={`${item.entityType}:${item.entityId}`} to={destination(item)}><span className="result-icon"><GroupIcon/></span><span><b>{item.title || labels[item.entityType] || item.entityType}</b><Snippet result={item}/><small>{item.context && item.body ? item.context : ''}{item.createdAt && <><Clock3/> {date(item.createdAt)}</>}<FileJson/> {item.sourcePath?.split('/').pop()}</small></span></Link>)}</section>; })}</div>{result.hasMore && <button className="load-more" onClick={loadMore} disabled={loadingMore}>{loadingMore ? <><LoaderCircle className="spin"/> Loading more results…</> : 'Load more results'}</button>}</>}</div>;
}
