/// <reference lib="webworker" />
import sqlite3InitModule from '@sqlite.org/sqlite-wasm'; import{MIGRATIONS,SCHEMA_VERSION}from'./schema'; import{getFallback,putFallback}from'./indexeddb-fallback'; import type{DatabaseRequest,DatabaseResponse,StorageMode}from'./types'; import type{NormalizedArchiveData}from'../archive/schemas/models';
type DB={exec:(options:string|Record<string,unknown>)=>unknown;transaction:(fn:()=>void)=>void};let db:DB,mode:StorageMode='indexeddb';
const send=(m:DatabaseResponse)=>postMessage(m);const exec=(sql:string,bind?:unknown[])=>db.exec({sql,bind,returnValue:'resultRows',rowMode:'object'} as Record<string,unknown>) as Record<string,unknown>[];
function migrate(){for(const sql of MIGRATIONS)db.exec(sql);db.exec({sql:'INSERT OR IGNORE INTO schema_migrations(version, applied_at) VALUES(?,?)',bind:[SCHEMA_VERSION,new Date().toISOString()]})}
function replace(data:NormalizedArchiveData){db.transaction(()=>{for(const t of['messages','conversations','posts','profiles'])db.exec(`DELETE FROM ${t}`);if(data.profile)db.exec({sql:'INSERT INTO profiles VALUES(?,?,?,?,?,?,?)',bind:[data.profile.id,data.profile.personId,data.profile.displayName,data.profile.username??null,data.profile.bio??null,data.profile.joinedAt??null,data.profile.source.path]});for(const p of data.posts)db.exec({sql:'INSERT INTO posts VALUES(?,?,?,?,?,?,?)',bind:[p.id,p.authorId??null,p.title??null,p.text??null,p.createdAt??null,p.source.path,p.source.index??null]});for(const c of data.conversations)db.exec({sql:'INSERT INTO conversations VALUES(?,?,?,?)',bind:[c.id,c.title??null,JSON.stringify(c.participantNames),c.source.path]});for(const m of data.messages)db.exec({sql:'INSERT INTO messages VALUES(?,?,?,?,?,?,?)',bind:[m.id,m.conversationId,m.senderName??null,m.text??null,m.sentAt??null,m.source.path,m.source.index??null]})})}
function hydrate(data:NormalizedArchiveData){replace(data)}
async function init(){const sqlite3=await sqlite3InitModule();if(sqlite3.oo1.OpfsDb){try{const OpfsDb=sqlite3.oo1.OpfsDb as unknown as new(filename:string,flags:string)=>DB;db=new OpfsDb('/socialvault.sqlite3','c');mode='opfs'}catch{db=new sqlite3.oo1.DB(':memory:','c') as unknown as DB}}else db=new sqlite3.oo1.DB(':memory:','c') as unknown as DB;migrate();if(mode==='indexeddb'){const saved=await getFallback();if(saved)hydrate(saved)}return{mode}}
self.onmessage=async(e:MessageEvent<DatabaseRequest>)=>{const r=e.data;try{if(r.type==='init'){send({id:r.id,ok:true,data:await init()});return}if(r.type==='replace'&&r.data){replace(r.data);if(mode==='indexeddb')await putFallback(r.data);send({id:r.id,ok:true});return}if(r.type==='profile'){const rows=exec('SELECT id, person_id personId, display_name displayName, username, bio, joined_at joinedAt, source_path sourcePath FROM profiles LIMIT 1');const x=rows[0];send({id:r.id,ok:true,data:x?{...x,source:{platform:'facebook',path:x.sourcePath}} as never:undefined});return}if(r.type==='posts'){const rows=exec('SELECT id, author_id authorId, title, body text, created_at createdAt, source_path sourcePath, source_index sourceIndex FROM posts ORDER BY created_at DESC');send({id:r.id,ok:true,data:rows.map(x=>({...x,source:{platform:'facebook',path:x.sourcePath,index:x.sourceIndex}})) as never});return}if(r.type==='conversations'){const rows=exec('SELECT id,title,participant_names participantNamesJson,source_path sourcePath,(SELECT COUNT(*) FROM messages m WHERE m.conversation_id=conversations.id) messageCount FROM conversations ORDER BY title');send({id:r.id,ok:true,data:rows.map(x=>({...x,participantIds:[],participantNames:JSON.parse(String(x.participantNamesJson)),source:{platform:'facebook',path:x.sourcePath}})) as never});return}if(r.type==='messages'){const rows=exec('SELECT id,conversation_id conversationId,sender_name senderName,body text,sent_at sentAt,source_path sourcePath,source_index sourceIndex FROM messages WHERE conversation_id=? ORDER BY sent_at',[r.conversationId]);send({id:r.id,ok:true,data:rows.map(x=>({...x,source:{platform:'facebook',path:x.sourcePath,index:x.sourceIndex}})) as never})}}catch(error){send({id:r.id,ok:false,error:error instanceof Error?error.message:String(error)})}};
