import type{NormalizedArchiveData}from'../archive/schemas/models';
import type{ImportState}from'./types';
const DB='socialvault-fallback',STORE='archives',META='metadata',KEY='current',STATE_KEY='import-state';
type FallbackState={data?:NormalizedArchiveData;importState?:ImportState};
function open(){return new Promise<IDBDatabase>((resolve,reject)=>{const req=indexedDB.open(DB,2);req.onupgradeneeded=()=>{const database=req.result;if(!database.objectStoreNames.contains(STORE))database.createObjectStore(STORE);if(!database.objectStoreNames.contains(META))database.createObjectStore(META);};req.onerror=()=>reject(req.error);req.onsuccess=()=>resolve(req.result)})}
export function putFallback(data?:NormalizedArchiveData){return open().then(database=>new Promise<void>((resolve,reject)=>{const tx=database.transaction(STORE,'readwrite');if(data)tx.objectStore(STORE).put(data,KEY);else tx.objectStore(STORE).delete(KEY);tx.oncomplete=()=>{database.close();resolve()};tx.onerror=()=>{database.close();reject(tx.error)}}))}
export function getFallback(){return open().then(database=>new Promise<NormalizedArchiveData|undefined>((resolve,reject)=>{const tx=database.transaction(STORE,'readonly'),get=tx.objectStore(STORE).get(KEY);get.onsuccess=()=>{database.close();resolve(get.result as NormalizedArchiveData|undefined)};get.onerror=()=>{database.close();reject(get.error)}}))}
export function putFallbackImportState(importState:ImportState){return open().then(database=>new Promise<void>((resolve,reject)=>{const tx=database.transaction(META,'readwrite');tx.objectStore(META).put(importState,STATE_KEY);tx.oncomplete=()=>{database.close();resolve()};tx.onerror=()=>{database.close();reject(tx.error)}}))}
export function getFallbackImportState(){return open().then(database=>new Promise<ImportState|undefined>((resolve,reject)=>{const tx=database.transaction(META,'readonly'),get=tx.objectStore(META).get(STATE_KEY);get.onsuccess=()=>{database.close();resolve(get.result as ImportState|undefined)};get.onerror=()=>{database.close();reject(get.error)}}))}
export function clearFallbackImportState(){return open().then(database=>new Promise<void>((resolve,reject)=>{const tx=database.transaction(META,'readwrite');tx.objectStore(META).delete(STATE_KEY);tx.oncomplete=()=>{database.close();resolve()};tx.onerror=()=>{database.close();reject(tx.error)}}))}
