import type{ActivityRecord,ActivityType,Album,ArchiveCoverage,ArchiveIdentity,ArchivePart,ArchiveSet,Comment,Connection,Conversation,ImportPartCheckpoint,ImportSession,Media,Message,NormalizedArchiveData,Person,Post,Profile}from'../archive/schemas/models';
export type StorageMode='opfs'|'indexeddb';export type SearchBackend='fts5'|'like';
export interface Page<T>{items:T[];nextCursor?:string;hasMore:boolean}
export interface ConversationPreview extends Conversation{messageCount:number;latestText?:string;latestSentAt?:string;isGroup:boolean}
export interface PersonSummary extends Person{participationCount:number;messageCount:number;postCount:number;mediaCount:number;commentCount:number;reactionCount:number;connectionCount:number;albumCount:number;sharedPostCount:number;sharedMediaCount:number;firstInteraction?:string;lastInteraction?:string}
export interface AlbumSummary extends Album{mediaCount:number}
export interface AlbumDetail{album:AlbumSummary;media:Media[]}
export interface MemoryRecord extends ActivityRecord{yearsAgo:number;calendarYear:number}
export interface ConnectionSummary extends Connection{person?:Person}
export interface SearchResult{entityType:string;entityId:string;title?:string;body?:string;context?:string;snippet?:string;createdAt?:string;conversationId?:string;sourcePath?:string;rank?:number}
export interface SearchResponse{items:SearchResult[];counts:Record<string,number>;hasMore:boolean;nextCursor?:string;backend:SearchBackend}
export interface ArchiveStatus{archiveSet?:ArchiveSet;parts:ArchivePart[];connectedPartIds:string[];missingPartIds:string[]}
export interface ArchiveStats{profiles:number;people:number;posts:number;comments:number;reactions:number;connections:number;albums:number;activities:number;conversations:number;messages:number;media:number;earliest?:string;latest?:string;warnings:number;sections:number;years:number[];diagnostics?:NormalizedArchiveData['diagnostics'];archiveIdentity?:ArchiveIdentity;archiveSet?:ArchiveSet;archiveParts?:ArchivePart[];importSession?:ImportSession;coverage?:ArchiveCoverage}
export interface ImportState{session?:ImportSession;checkpoints:ImportPartCheckpoint[];coverage?:ArchiveCoverage}
export interface RebuildResult{kind:'search'|'activity';rows:number;completedAt:string}
export type DiagnosticsReport=Record<string,unknown>;
export type DatabaseRequest={id:number;type:'init'|'replace'|'profile'|'people'|'person'|'posts'|'post'|'conversations'|'messages'|'search'|'stats'|'media'|'connections'|'albums'|'album'|'memories'|'activity'|'archive-identity'|'archive-status'|'media-cache'|'import-state'|'begin-import'|'import-part'|'import-batch'|'update-media-sources'|'update-import'|'cancel-import'|'interrupt-import'|'skip-import-part'|'fail-import-part'|'retry-import-part'|'restart-import'|'rebuild-search'|'rebuild-activity'|'coverage'|'diagnostics';data?:NormalizedArchiveData;session?:ImportSession;checkpoint?:ImportPartCheckpoint;part?:ArchivePart;sessionId?:string;conversationId?:string;personId?:string;postId?:string;albumId?:string;cursor?:string;limit?:number;sort?:'newest'|'oldest';year?:number;month?:number;day?:number;query?:string;activityType?:ActivityType;connectionType?:Connection['type'];mediaType?:Media['mediaType'];mediaPath?:string;byteSize?:number;entityType?:string;from?:string;to?:string;status?:string;errorMessage?:string;force?:boolean};
export type DatabaseResult=Profile|PersonSummary|PersonSummary[]|Post|Post[]|Comment[]|ConnectionSummary[]|AlbumSummary|AlbumSummary[]|AlbumDetail|ConversationPreview[]|Message[]|Media[]|MemoryRecord[]|ActivityRecord[]|Page<Post>|Page<PersonSummary>|Page<ConversationPreview>|Page<Message>|Page<Media>|Page<ConnectionSummary>|Page<AlbumSummary>|Page<MemoryRecord>|Page<ActivityRecord>|SearchResponse|ArchiveStats|ArchiveIdentity|ArchiveStatus|ImportState|ImportSession|ImportPartCheckpoint|RebuildResult|ArchiveCoverage|DiagnosticsReport|{mode:StorageMode;searchBackend:'fts5'|'like'}|undefined;
export type DatabaseResponse={id:number;ok:true;data?:DatabaseResult}|{id:number;ok:false;error:string};
